### PR TITLE
Task 6 - SQS & SNS, Async Microservices Communication

### PR DESCRIPTION
**Pull request by bwire**
- Task 6.1 
  - New lambda catalogBatchProcess  and SQS queue created under the product-service;
  - SQS configured to trigger the new lambda;
  - The amount of messages processed by the lambda can be configured via SQS_BATCH_SIZE environment variable (see `product-service/stack.ts`);

- Task 6.2
  - importFileParser lambda (import-service) updated to send parsed blocks of data to the SQS queue;

- Task 6.3
  - New SNS topic createProductTopic creates in product-service and two subscriptions added - one for all messages, the second one according to the filtering policy (`count` value in the message data less than or equal to 10);
  - catalogBatchProcess lambda now publish messages with the newly created product data to the SNS topic import-product-topic;

AWS CDK configuration for the product-service: `product-service/stack.ts`;
AWS CDK configuration for the import-service: `import-service/stack.ts`;

- Additional tasks:
  - unit tests added to cover catalogBatchProcess lambda (hander and service method - `product-service/test`)
  - filter policy is used to send messages to a different e-mail (as described above);

Also PR contains code to update both services to make them use the latest was-sdk v3 (just for the information).

Link to deployed front-end application functionality: https://d1eot7ucp9tkae.cloudfront.net

Now the backend part uses DynamoDB under the hood, but can be configured to use PostgeDB (by changing USE_NOSQL_DB environment variable).

Example css-file, I used for uploading: 
[test.csv](https://github.com/bwire/aws-shop-backend/files/11886834/test.csv)

I have utilised the ability of the parser to work with different separators - so now it is adjusted to work with ';' separator!!!

### CODE REVIEW

**Comment by december-man** [comment]
Hello there! Unfortunately, the CSV upload is not working for me, here's what I'm trying to do:
1. Upload a `csv-tester.csv` file
2. Check the console
3. Refresh the page
4. See the products from the .csv file

#### `csv-tester.csv` has the following structure:
image
#### Console shows status 200 on upload:
image
#### But something strange happens upon refresh (I'm catching 403 Error):
image
#### Unfortunately, no new products were added:
image

### Can you please share the info from cloudwatch logs?
### Maybe the CSV formatting is wrong.

**Comment by bwire** [comment]
Hi. it happens to me as well. But I don't think this is the problem for me or you - if I refresh I've got the same error. But I don't want to fix all issues in FE repository :) 
I think it's because the direct access to this url (I mean /admin/products) is forbidden and you can only go there through the menu. If you try to refresh or enter this url by hand - you got this error.

**Comment by december-man** [comment]
> Hi. it happens to me as well. But I don't think this is the problem for me or you - if I refresh I've got the same error. But I don't want to fix all issues in FE repository :) I think it's because the direct access to this url (I mean /admin/products) is forbidden and you can only go there through the menu. If you try to refresh or enter this url by hand - you got this error.

Yeah I got it, but then again - its hard to verify your work if I cannot just upload some products from a .csv file. Imagine how simple it would be. Now I have to deal with this scrutiny of checking all the scripts, not just the SNS part.
Also I don't think this access problem is important here. I got the 200 response from the upload button, that means you've pulled changes to the FE (`/import` in `ApiPaths.ts`) from task 5. The question is, why its not being parsed, pushed to the database and returned to FE using task 4 scripts? I mean, we've already done that in task 4 with `/products` link in `ApiPaths.ts`. Why not just pull this version of FE (task 4) to this project?

**Comment by bwire** [comment]
Sorry, I'm afraid - I don't understand the problem. Can you upload your file at all or not? Can we talk in discord?
And what should I pull? I've just tried to upload my file and it worked well. Please, attach yours - I'll try it.

**Comment by december-man** [comment]
> Sorry, I'm afraid - I don't understand the problem. Can you upload your file at all or not? Can we talk in discord?

Already answered you on discord, lets discuss it there.

UPD: Issue was in `.csv` file separator (semicolon instead of a comma) and the 403 error is not critical for the task itself.

**Pull request merged**
